version: '3.7'

services:
  rest-api:
    container_name: rest-api
    resetart: unless-stopped
    enviroment:
      - NODE_ENV=production
    build:
        context: ./
    ports:
      - 5000:5000
